// Generated by scripts/generate-env.js — do not edit by hand on Vercel.
export const SUPABASE_URL = "https://vazkrvcnczdyjpflpnit.supabase.co";
export const SUPABASE_ANON_KEY = "sb_publishable_C3JudYjscrezMsBb33Bnow_IKs9bUGs";
